Repository Def-Hacks-CS-Outreach/def-hacks-learn, pull requests merged in 2020-11, with the labels that each got.

#28 Making the login input field control
  src/components/authscreens/Login.js
  src/pages/ExistAccount.js
Labels: Status: :vertical_traffic_light: Awaiting

#30 Feature: Update user settings (UI), removed footer temporarily due to style bugs.
  package-lock.json
  package.json
  src/App.js
  src/components/authscreens/Recover.js
  src/components/common/Footer.js
  src/pages/ExistAccount.js
  src/pages/ExistUser.js
  src/pages/Home.js
  src/styles/about.css
  src/styles/exist.css
  src/styles/footer.css
  src/styles/home.css
Labels: Fix: :desktop_computer: UI, Status: :vertical_traffic_light: Awaiting, Status: Accepted

#31 Add react-sticky package
  package-lock.json
  package.json
Labels: Bug solver :star:, Status: :vertical_traffic_light: Awaiting

#38 Add Codacy Quality badge
  README.md
Labels: Status: :vertical_traffic_light: Awaiting, documentation, enhancement

#52 Change Nav to Link DOMs in Navbar and add ESLint YAML file
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ESLint-CI.yml
  src/components/common/Navbar.js
  src/styles/navbar.css
Labels: enhancement
